### ISSUE TITLE
FlexiProvider Integration: manual key entry in HMacMD5 not working

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#10]
Open the HMacMD5 wizard (FlexiProvider Integration) and select "Custom key" as key source. Keep the defaults and click on Finish.
1) A dialog pops up, asking for the keys password. This is not correct, the keystore is not used at all with a custom key.
2) Entering the default password results in the following expection:

java.lang.NullPointerException
    at org.jcryptool.crypto.keystore.backend.KeyStoreManager.getSecretKey(KeyStoreManager.java:401)
    at org.jcryptool.crypto.flexiprovider.engines.mac.MacEngine.init(MacEngine.java:61)
    at org.jcryptool.crypto.flexiprovider.engines.listener.PerformOperationListener.performOperation(PerformOperationListener.java:75)
    at org.jcryptool.crypto.flexiprovider.operations.engines.PerformOperationManager.firePerformOperation(PerformOperationManager.java:44)
    at org.jcryptool.crypto.flexiprovider.integrator.IntegratorAction.run(IntegratorAction.java:340)
    at org.jcryptool.core.operations.algorithm.ShadowAlgorithmAction.run(ShadowAlgorithmAction.java:99)
    at org.jcryptool.core.views.content.palette.AlgorithmPaletteViewer$2.run(AlgorithmPaletteViewer.java:237)
    at org.jcryptool.core.views.content.palette.AlgorithmPaletteViewer$3.mouseDoubleClick(AlgorithmPaletteViewer.java:249)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:195)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2696)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2660)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2494)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:674)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:667)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.jcryptool.core.Application.start(Application.java:33)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

**Comment by simlei** [comment]
Could not reproduce, works fine for me. possibly solved by b612c65
