### ISSUE TITLE
Keystore Uninitialized 

### ISSUE THREAD

**Issue by TreyBlo** [jcryptool/core#145]
Ive tried making new keys and contact, but it keeps giving me an Error saying uninitialized. 

With these exceptions:
java.security.KeyStoreException: Uninitialized keystore
	at java.security.KeyStore.setEntry(KeyStore.java:1555)
	at org.jcryptool.crypto.keystore.backend.KeyStoreManager.addSecretKey(KeyStoreManager.java:579)
	at org.jcryptool.crypto.keystore.ui.actions.AbstractKeyStoreHandler.addSecretKeyStatic(AbstractKeyStoreHandler.java:56)
	at org.jcryptool.crypto.keystore.ui.actions.AbstractKeyStoreHandler.addSecretKey(AbstractKeyStoreHandler.java:62)
	at org.jcryptool.crypto.keystore.ui.actions.AbstractNewKeyStoreEntryHandler.performNewKeyAction(AbstractNewKeyStoreEntryHandler.java:23)
	at org.jcryptool.crypto.flexiprovider.keystore.actions.NewSymmetricKeyHandler.execute(NewSymmetricKeyHandler.java:108)
	at org.jcryptool.crypto.keystore.ui.actions.ShadowKeyStoreHandler$1.run(ShadowKeyStoreHandler.java:60)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:147)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4932)
	at org.jcryptool.crypto.keystore.ui.actions.ShadowKeyStoreHandler.execute(ShadowKeyStoreHandler.java:57)
	at org.eclipse.core.commands.Command.executeWithChecks(Command.java:497)
	at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:490)
	at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
	at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:403)
	at org.eclipse.ui.menus.CommandContributionItem.handleWidgetSelection(CommandContributionItem.java:824)
	at org.eclipse.ui.menus.CommandContributionItem.lambda$3(CommandContributionItem.java:801)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4319)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4143)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3760)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:636)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:563)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:151)
	at org.jcryptool.core.Application.start(Application.java:45)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:595)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1501)

**Comment by grthor** [comment]
Hi @TreyBlo, thaks for reporting this issue. Can you tell me which keys do you tried to create (ElGamal, RSA, ...). Maybe you could take a screenshot of the page where the error occurs. That would help me reproduce and fix the bug. 
Best regards, Thorben

**Comment by grthor** [comment]
Yet another question: Which version of the JCT do you use? The version number of the newer JCT versions is in the title bar of the program.

**Comment by TreyBlo** [comment]
version 0.9.10, and I've tried multiple types of keys. Thank you very much!
<img width="1440" alt="Screen Shot 5779-11-05 at 12 55 33" src="https://user-images.githubusercontent.com/52668340/60828309-12836e80-a180-11e9-9142-3fa9274dc6d1.png">

**Comment by grthor** [comment]
Thank you for your prompt reply. 
Please try the following solution to solve the problem.
1. Close JCrypTool
2. Delete the .jcryptool folder (Unfortunately, I can not tell you where it is because I do not use a Mac. For windows, it is located under c:/users/username/documents. Maybe this helps a bit.)
3. Open the JCrypTool

This replaces the existing keystore with a standard keystore, which comes with version 09.10. The background is that Oracle has introduced a restrictive policy for loading the keystore with Java Update 8u171 (April 17, 2018). If you have a newer Java version than 8u171, but an old keystore, it can not be loaded anymore.
