### ISSUE TITLE
p2 unable to read https://www.cryptool.org/jct/update/content.xml - No updates

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#201]
p2 (the thing that checks for JCT updates) could not connect with https://www.cryptool.org/jct/update/content.xml and https://www.cryptool.org/jct/update/p2.index. This is a problem that must be solved before Release 1.0, because if not the automatic updates will not work when we release version 1.1.

The following exception is printed to the error log:
```
eclipse.buildId=unknown
java.version=11.0.5
java.vendor=AdoptOpenJDK
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -data @user.home/Documents/.jcryptool

!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2020-04-23 19:23:23.607
!MESSAGE Connection to https://www.cryptool.org/jct/update/p2.index failed on Received fatal alert: handshake_failure. Retry attempt 0 started
!STACK 0
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Unknown Source)
	at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        ...
```

I investigated the problem and my assumption is, that the JCT and the website have no common cipher suite.

The website accepts the following cipher suits:
```
thorben@thorben-VirtualBox:/media$ nmap --script ssl-enum-ciphers -p 443 cryptool.org

Starting Nmap 7.60 ( https://nmap.org ) at 2020-04-23 19:31 CEST
Nmap scan report for cryptool.org (137.193.65.237)
Host is up (0.029s latency).

PORT    STATE SERVICE
443/tcp open  https
| ssl-enum-ciphers: 
|   TLSv1.2: 
|     ciphers: 
|       TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (secp384r1) - A
|       TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 (secp384r1) - A
|       TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (dh 4096) - A
|     compressors: 
|       NULL
|     cipher preference: server
|_  least strength: A

Nmap done: 1 IP address (1 host up) scanned in 5.38 seconds
```

I could not figure out, which cipher suites our JRE supports. 

Figuring out, which cipher suites the JRE supports would be the next step in solving this issue.

**Comment by grthor** [comment]
Fixed for now by forcing the JCT to use TLS 1.2 by default. This is done by adding `-Djdk.tls.client.protocols=TLSv1.2` to the VM arguments in org.jcryptool.product/jcryptool.product Commit: https://github.com/jcryptool/core/commit/e71c3f2c8d3b7a4753435036ff10c66c1db0543b. 

This is no great solution, because it enforces to use an older TLS version. TLS 1.3 is the default now.

**Comment by grthor** [comment]
Jetzt ist es sauber gefixt.

Das Problem war die Reihenfolge, in der verschiedenen im JCT vorhanden Krypto-Provider genutzt wurden. Die vier Krypto-Provider aus dem Flexiprovider wurden als erstes genutzt, dann kamen die 13 SUN Krypto-Provider, dann BouncyCastle. 
Das Problem war, dass die Flexiprovider Krypto-Provider nur "alte" Verfahren zum Schlüsselaustausch unterstützen. Bei TLS 1.3 Verbindungen hatten so cryptool.org und das JCT keine gemeinsamen Verfahren zum Schlüsselaustausch. Anstatt jetzt zu sagen "Unterstütze ich nicht, soll ein anderer Provider sich drum kümmern" wurde eine Exception geworfen und der Verbindungsaufbau wurde abgebrochen.
Ich habe die Reihenfolge jetzt so geändert, dass die SUN Provider als erstes genutzt werden, dann die Flexiprovider und dann BC. Jetzt werden auch die neuen Verfahren wie secp384r1 unterstützt, die der cryptool.org-Server aktzeptiert.

Negative Auswirkungen durch die Änderung der Reihenfolge konnte ich nicht feststellen.

Commits die das Problem beheben:
- https://github.com/jcryptool/core/commit/eff6b3d2d69c92e3024bd46e4af2973a35901749
- https://github.com/jcryptool/core/commit/2f913ae0dcc7e517a69d0fe5dec8a36290b51e62

**Das Problem ist jetzt abschließend gefixt!**

**Comment by grthor** [comment]
The handshake between server and jct fails again. I assume the flexiprovider is used as primary crypto provider instead of the sun crypto provider. Because of that no commom cipher suites are available.

```
!ENTRY org.eclipse.equinox.p2.transport.ecf 2 0 2020-07-16 18:54:58.322
!MESSAGE Connection to https://www.cryptool.org/jct/update/p2.index failed on Received fatal alert: handshake_failure. Retry attempt 0 started
!STACK 0
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
```

I will take a look into that.

**Comment by grthor** [comment]
I can not reproduce the error anymore.

The logs are now clear, no exceptions and the handshake is successful.

Maybe I just got some old files in my .jcryptool folder.

I will close the issue again.
