### ISSUE TITLE
SSL/TLS-Handshake simulation NoSuchProviderException

### ISSUE THREAD

**Issue by nomisge** [jcryptool/core#237]
On a Linux system with the latest jcryptool release 1.0.3 when using the SSL-TLS-Handshake simulation with following settings:  
- Client: TLS 1.2 with generated random value any cipher suite
- Server: same as client, different generated random value

I get following error:
```
java.security.NoSuchProviderException: no such provider: BC
	at java.base/sun.security.jca.GetInstance.getService(Unknown Source)
	at java.base/sun.security.jca.GetInstance.getInstance(Unknown Source)
	at java.base/java.security.KeyPairGenerator.getInstance(Unknown Source)
	at org.jcryptool.visual.ssl.protocol.Crypto.generateGenerator(Crypto.java:304)
	at org.jcryptool.visual.ssl.views.ServerCertificateComposite.calculateKeyExchange(ServerCertificateComposite.java:438)
	at org.jcryptool.visual.ssl.views.ServerCertificateComposite.startStep(ServerCertificateComposite.java:276)
	at org.jcryptool.visual.ssl.views.SslView.nextStep(SslView.java:303)
	at org.jcryptool.visual.ssl.views.ServerHelloComposite$5.mouseUp(ServerHelloComposite.java:194)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5745)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1427)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5013)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4507)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:153)
	at org.jcryptool.core.Application.start(Application.java:51)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
```

**Comment by grthor** [comment]
Hi, thanks for your issue report. I will take a look into this in the next days and let you know what I find and how to fix it.
Best regards 
Thorben

**Comment by grthor** [comment]
Hi, the problem could be fixed.
I released a new version that is available here: https://github.com/jcryptool/core/releases/tag/Weekly-Build--2021-02-22
Best regards
Thorben
