### ISSUE TITLE
Flexiprovider Integration: PBES2 Algorithm Initialization fails

### ISSUE THREAD

**Issue by anatolibarski** [jcryptool/core#50]
Double click PBES2 Algorithm in Algorithms view, submit the configuration dialog with default parameters.

When providing specific parameters like F5, 10, 128, F5, the algorithm will be added to operations view without exception.

Other PBE.. algorithm can be added with default parameters without exception

The problem seems to be in the definition of PBES2ParameterSpec inside 
/de.flexiprovider/xml/algorithms.xml

java.lang.NoSuchMethodException: de.flexiprovider.core.pbe.PBES2ParameterSpec.<init>([B, int, int, [B)
    at java.lang.Class.getConstructor0(Class.java:2730)
    at java.lang.Class.getConstructor(Class.java:1676)
    at org.jcryptool.crypto.flexiprovider.reflect.Reflector.instantiateParameterSpec(Reflector.java:226)
    at org.jcryptool.crypto.flexiprovider.algorithms.ui.wizards.AlgorithmWizard.performFinish(AlgorithmWizard.java:93)
    at org.eclipse.jface.wizard.WizardDialog.finishPressed(WizardDialog.java:827)
    at org.eclipse.jface.wizard.WizardDialog.buttonPressed(WizardDialog.java:432)
    at org.eclipse.jface.dialogs.Dialog$2.widgetSelected(Dialog.java:624)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:240)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
    at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
    at org.eclipse.jface.window.Window.open(Window.java:801)
    at org.jcryptool.crypto.flexiprovider.algorithms.AlgorithmsManager.performCipherCalled(AlgorithmsManager.java:141)
    at org.jcryptool.crypto.flexiprovider.algorithms.AlgorithmsManager.algorithmCalled(AlgorithmsManager.java:69)
    at org.jcryptool.crypto.flexiprovider.algorithms.ui.views.FlexiProviderAlgorithmsView$1.run(FlexiProviderAlgorithmsView.java:100)
    at org.jcryptool.crypto.flexiprovider.algorithms.ui.views.FlexiProviderAlgorithmsView$2.mouseDoubleClick(FlexiProviderAlgorithmsView.java:134)
    at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:195)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1053)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4165)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3754)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.jcryptool.core.Application.start(Application.java:33)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:344)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:179)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:622)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:577)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1410)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1386)

**Comment by simlei** [comment]
I am currently working on a complete integration of the BouncyCastle crypto provider. FlexiProvider is already merged into Bouncycastle and not longer maintained and the new-release-updating issues will be appropriately addressed in the future. To be raised again with fresh informations if necessary.
