### ISSUE TITLE
File Explorer's View Menu is empty, ClassCastException

### ISSUE THREAD

**Issue by hfriedr** [jcryptool/core#94]
The View Menu of File Explorer shows several empty entries, the Eclipse Console shows a ClassCastException:

!ENTRY org.eclipse.ui 4 0 2015-02-11 18:32:10.710
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ClassCastException: org.eclipse.e4.ui.workbench.renderers.swt.HandledContributionItem cannot be cast to org.eclipse.ui.menus.CommandContributionItem
	at org.jcryptool.fileexplorer.views.FileExplorerView$5.menuAboutToShow(FileExplorerView.java:356)
	at org.eclipse.jface.action.MenuManager.fireAboutToShow(MenuManager.java:352)
	at org.eclipse.jface.action.MenuManager.handleAboutToShow(MenuManager.java:492)
	at org.eclipse.jface.action.MenuManager.access$1(MenuManager.java:487)
	at org.eclipse.jface.action.MenuManager$2.menuShown(MenuManager.java:519)

**Comment by hfriedr** [comment]
fixed on Feb 18, 2015
